# -- ros system --
out_twist_topic: twist_cmd
in_refpath_topic: reference_path
in_odom_topic: odom
robot_frame_id: base_link
map_frame_id: map

# -- control system --
control_sampling_time: 0.1 # [s] control interval
reference_speed: 1.0 # [m/s]

# -- C/GMRES solver parameters --
Tf: 1.0 # Length of predictive horizon in C/GMRES [s]
alpha: 0.5 # The length horizon at time t is given by T_f * (1-exp(-alpha*t))
N: 10 # The number of discrete of the predictive horizon
finite_distance_increment: 0.0002 # Step length of the finite difference in C/GMRES method
zeta: 62.5 # A parameter for stabilization of the C/GMRES method
kmax: 5 # dimension of the Krylov subspace and maximum iteration number

# -- MPC parameters --
weight_lat_error: 1.0 # Weight for lateral error from reference path in stage cost
weight_yaw_error: 1.0 # Weight for yaw error from reference path in stage cost
terminal_weight_lat_error: 1.0 # Weight for lateral error from reference path in terminal cost
terminal_weight_yaw_error: 1.0 # Weight for yaw error from reference path in terminal cost
weight_input_angular_yaw: 1.0 # Weight for angular velocity input
weight_input_twist_x: 1.0 # Weight for forward/backward velocity input
